//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityBot.Persistence.MediaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaBase", Namespace="http://schemas.datacontract.org/2004/07/MediaServices.Data")]
    [System.SerializableAttribute()]
    public partial class MediaBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualityBot.Persistence.MediaService.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualityBot.Persistence.MediaService.FileType FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualityBot.Persistence.MediaService.Date MediaDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MediaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MediaOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QualityBot.Persistence.MediaService.Place MediaPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OriginalOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaveTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UploadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualityBot.Persistence.MediaService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureCode {
            get {
                return this.CultureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureCodeField, value) != true)) {
                    this.CultureCodeField = value;
                    this.RaisePropertyChanged("CultureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualityBot.Persistence.MediaService.FileType FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((this.FileTypeField.Equals(value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualityBot.Persistence.MediaService.Date MediaDate {
            get {
                return this.MediaDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaDateField, value) != true)) {
                    this.MediaDateField = value;
                    this.RaisePropertyChanged("MediaDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MediaId {
            get {
                return this.MediaIdField;
            }
            set {
                if ((this.MediaIdField.Equals(value) != true)) {
                    this.MediaIdField = value;
                    this.RaisePropertyChanged("MediaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MediaOwner {
            get {
                return this.MediaOwnerField;
            }
            set {
                if ((this.MediaOwnerField.Equals(value) != true)) {
                    this.MediaOwnerField = value;
                    this.RaisePropertyChanged("MediaOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QualityBot.Persistence.MediaService.Place MediaPlace {
            get {
                return this.MediaPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaPlaceField, value) != true)) {
                    this.MediaPlaceField = value;
                    this.RaisePropertyChanged("MediaPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OriginalOwner {
            get {
                return this.OriginalOwnerField;
            }
            set {
                if ((this.OriginalOwnerField.Equals(value) != true)) {
                    this.OriginalOwnerField = value;
                    this.RaisePropertyChanged("OriginalOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaveToken {
            get {
                return this.SaveTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SaveTokenField, value) != true)) {
                    this.SaveTokenField = value;
                    this.RaisePropertyChanged("SaveToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Date", Namespace="http://schemas.datacontract.org/2004/07/MediaShared.Data")]
    [System.SerializableAttribute()]
    public partial class Date : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateString {
            get {
                return this.DateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.DateStringField, value) != true)) {
                    this.DateStringField = value;
                    this.RaisePropertyChanged("DateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateValue {
            get {
                return this.DateValueField;
            }
            set {
                if ((this.DateValueField.Equals(value) != true)) {
                    this.DateValueField = value;
                    this.RaisePropertyChanged("DateValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://schemas.datacontract.org/2004/07/MediaShared.Data")]
    [System.SerializableAttribute()]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PlaceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatitudeValue {
            get {
                return this.LatitudeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeValueField, value) != true)) {
                    this.LatitudeValueField = value;
                    this.RaisePropertyChanged("LatitudeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongitudeValue {
            get {
                return this.LongitudeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeValueField, value) != true)) {
                    this.LongitudeValueField = value;
                    this.RaisePropertyChanged("LongitudeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PlaceId {
            get {
                return this.PlaceIdField;
            }
            set {
                if ((this.PlaceIdField.Equals(value) != true)) {
                    this.PlaceIdField = value;
                    this.RaisePropertyChanged("PlaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceString {
            get {
                return this.PlaceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceStringField, value) != true)) {
                    this.PlaceStringField = value;
                    this.RaisePropertyChanged("PlaceString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/MediaServices.Data.Enums")]
    public enum Category : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileType", Namespace="http://schemas.datacontract.org/2004/07/MediaShared.Common.Utils")]
    public enum FileType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tabular = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaService.IMediaStore")]
    public interface IMediaStore {
        
        // CODEGEN: Generating message contract since the wrapper name (MediaFile) of message MediaFile does not match the default value (SaveFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaStore/SaveFile", ReplyAction="http://tempuri.org/IMediaStore/SaveFileResponse")]
        QualityBot.Persistence.MediaService.SaveFileResponse SaveFile(QualityBot.Persistence.MediaService.MediaFile request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MediaFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MediaFile {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid ApplicationId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string ContainerPath;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long FileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public QualityBot.Persistence.MediaService.MediaBase MediaMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileStream;
        
        public MediaFile() {
        }
        
        public MediaFile(System.Guid ApplicationId, string ContainerPath, string FileName, long FileSize, QualityBot.Persistence.MediaService.MediaBase MediaMetaData, System.IO.Stream FileStream) {
            this.ApplicationId = ApplicationId;
            this.ContainerPath = ContainerPath;
            this.FileName = FileName;
            this.FileSize = FileSize;
            this.MediaMetaData = MediaMetaData;
            this.FileStream = FileStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid MediaGuid;
        
        public SaveFileResponse() {
        }
        
        public SaveFileResponse(System.Guid MediaGuid) {
            this.MediaGuid = MediaGuid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMediaStoreChannel : QualityBot.Persistence.MediaService.IMediaStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaStoreClient : System.ServiceModel.ClientBase<QualityBot.Persistence.MediaService.IMediaStore>, QualityBot.Persistence.MediaService.IMediaStore {
        
        public MediaStoreClient() {
        }
        
        public MediaStoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaStoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QualityBot.Persistence.MediaService.SaveFileResponse QualityBot.Persistence.MediaService.IMediaStore.SaveFile(QualityBot.Persistence.MediaService.MediaFile request) {
            return base.Channel.SaveFile(request);
        }
        
        public System.Guid SaveFile(System.Guid ApplicationId, string ContainerPath, string FileName, long FileSize, QualityBot.Persistence.MediaService.MediaBase MediaMetaData, System.IO.Stream FileStream) {
            QualityBot.Persistence.MediaService.MediaFile inValue = new QualityBot.Persistence.MediaService.MediaFile();
            inValue.ApplicationId = ApplicationId;
            inValue.ContainerPath = ContainerPath;
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.MediaMetaData = MediaMetaData;
            inValue.FileStream = FileStream;
            QualityBot.Persistence.MediaService.SaveFileResponse retVal = ((QualityBot.Persistence.MediaService.IMediaStore)(this)).SaveFile(inValue);
            return retVal.MediaGuid;
        }
    }
}
